version: "3"
services:
  valheim:
    image: ghcr.io/lloesche/valheim-server
    env_file: .env
    volumes:
      - $HOME/valheim-server/config:/config
      - $HOME/valheim-server/data:/opt/valheim
    ports:
      - 2456-2457:2456-2457/udp
    cap_add:
      - SYS_NICE