services:
  minecraft:
    image: itzg/minecraft-server
    restart: unless-stopped
    ports:
      - 25565:25565
    environment:
      INIT_MEMORY: 1G
      MAX_MEMORY: 4G
      EULA: "TRUE"
      MOTD: A Super Secret Minecraft Server
      DIFFICULTY: normal
      SPAWN_PROTECTION: 16
      RESOURCE_PACK: https://github.com/connorhsm/connorhsm/releases/download/mc-resource-pack/VanillaTweaks_r834374_MC1.21.x.zip
      OPS: |
        tahtekcub
      RCON_CMDS_STARTUP: |
        gamerule playersSleepingPercentage 0
      
    tty: true
    stdin_open: true
    volumes:
      - $HOME/minecraft-server/data:/data
