version: "3"
services:
  minecraft:
    image: itzg/minecraft-server
    restart: unless-stopped
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
    tty: true
    stdin_open: true
    volumes:
      - $HOME/minecraft-server/data:/data
