services:
  minecraft:
    image: itzg/minecraft-server
    restart: unless-stopped
    ports:
      - 25565:25565
    environment:
      INIT_MEMORY: 1G
      MAX_MEMORY: 4G
      EULA: "TRUE"
      MOTD: "A Super Secret Minecraft Server"
      DIFFICULTY: "normal"
      SPAWN_PROTECTION: 16
      OPS: |
        tahtekcub
      RCON_CMDS_STARTUP: |
        gamerule playersSleepingPercentage 0
      
    tty: true
    stdin_open: true
    volumes:
      - $HOME/minecraft-server/data:/data
