name: Sync AHAP
on:
  workflow_dispatch:
  schedule:
    # At 23:05 UTC every day
    - cron:  '5 23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync
      run: |
        git clone --mirror https://github.com/jasonrohrer/AnotherPlanetData
        cd AnotherPlanetData.git/
        git remote add mirror https://connorhsm:$GITHUB_TOKEN@github.com/connorhsm/AnotherPlanetData-mirror
        git push --mirror mirror
      env:
        GITHUB_TOKEN: ${{ secrets.AHAP_SYNCER_GITHUB_TOKEN }}
